export const FETCH_AUTHUSERS = "FETCH_AUTHUSERS";
export const FETCH_AUTHUSERS_SUCCESS = "FETCH_AUTHUSERS_SUCCESS";
export const FETCH_AUTHUSERS_FAILURE = "FETCH_AUTHUSERS_FAILURE";

export const ADD_AUTHUSER = "ADD_AUTHUSER";
export const ADD_AUTHUSER_SUCCESS = "ADD_AUTHUSER_SUCCESS";
export const ADD_AUTHUSER_FAILURE = "ADD_AUTHUSER_FAILURE";

export const UPDATE_AUTHUSER = "UPDATE_AUTHUSER";
export const UPDATE_AUTHUSER_SUCCESS = "UPDATE_AUTHUSER_SUCCESS";
export const UPDATE_AUTHUSER_FAILURE = "UPDATE_AUTHUSER_FAILURE";

export const REMOVE_AUTHUSER = "REMOVE_AUTHUSER";
export const REMOVE_AUTHUSER_SUCCESS = "REMOVE_AUTHUSER_SUCCESS";
export const REMOVE_AUTHUSER_FAILURE = "REMOVE_AUTHUSER_FAILURE";
