export const FETCH_BOOKMARKS_LIST = 'FETCH_BOOKMARKS_LIST';
export const ADD_BOOKMARK_REQUEST = 'ADD_BOOKMARK_REQUEST';
export const ADD_CATEGORY_REQUEST = 'ADD_CATEGORY_REQUEST';
export const DELETE_BOOKMARK_REQUEST = 'DELETE_BOOKMARK_REQUEST';
export const SEARCH_BOOKMARKS_REQUEST = 'SEARCH_BOOKMARKS_REQUEST';
export const CHANGE_PAGINATION_REQUEST = 'CHANGE_PAGINATION_REQUEST';

