import "./globals.css";
import type { Metadata } from "next";
import Header from "@/components/header";
import "bootstrap/dist/css/bootstrap.min.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        <div className="container mt-5">{children}</div>
      </body>
    </html>
  );
}
