import './globals.css';
import type { Metadata } from 'next';
import 'bootstrap/dist/css/bootstrap.min.css';
import { FilterBookmarksProvider } from '../contexts/FilterBookmarksContext';
import SearchInput from '@/components/SearchInput';
import ModalsComponent from '@/components/modalscomp';
import { Provider } from 'react-redux';
import BulkTemplatesData from '@/components/bulktemplates';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {/* <FilterBookmarksProvider>
          <div className="container mt-5">
            <div className="row mb-4">
              <div className="col">
                <h1>Bookmarks Manager</h1>
              </div>
              <div className="col-auto">
                <ModalsComponent />
              </div>
            </div>
            <div className="row mb-4">
              <div className="col">
                <SearchInput />
              </div>
            </div>
            {children}
          </div>
        </FilterBookmarksProvider> */}
        <BulkTemplatesData />
      </body>
    </html>
  );
}
