export const bulkhistory = {
  responses: [],
  bulkNotificationHistories: [
    {
      recipientId: '20961',
      recipientAddress: '0000259322',
      recipientParameters: '26993,PEN,PL',
      messageType: 'T',
      subject: 'Loan Application Pending',
      message:
        'Thank you! We have received your application %% and it is under review.',
      status: 'S',
      updatedDate: 1757440927568,
      acctnbr: null,
      bounced: false,
    },
    {
      recipientId: '20961',
      recipientAddress: '2102221000',
      recipientParameters: '26993,PEN,PL',
      messageType: 'T',
      subject: 'Loan Application Pending',
      message:
        'Thank you! We have received your application %% and it is under review.',
      status: 'S',
      updatedDate: 1757440927568,
      acctnbr: null,
      bounced: false,
    },
    {
      recipientId: '20961',
      recipientAddress: '2102221000',
      recipientParameters: 'Ezekiel,27836,PEN',
      messageType: 'T',
      subject: 'Loan Application Pending',
      message:
        'Thank you! We have received your application %% and it is under review.',
      status: 'S',
      updatedDate: 1757451114210,
      acctnbr: '27836',
      bounced: false,
    },
    {
      recipientId: '20961',
      recipientAddress: '0000259322',
      recipientParameters: 'Ezekiel,27094,PEN',
      messageType: 'T',
      subject: 'Loan Application Pending',
      message:
        'Thank you! We have received your application %% and it is under review.',
      status: 'S',
      updatedDate: 1757451114210,
      acctnbr: '27094',
      bounced: false,
    },
    {
      recipientId: '20961',
      recipientAddress: '2102221000',
      recipientParameters: 'Ezekiel,27094,PEN',
      messageType: 'T',
      subject: 'Loan Application Pending',
      message:
        'Thank you! We have received your application %% and it is under review.',
      status: 'S',
      updatedDate: 1757451114210,
      acctnbr: '27094',
      bounced: false,
    },
    {
      recipientId: '20961',
      recipientAddress: '2102221000',
      recipientParameters: 'Ezekiel,27094,PEN',
      messageType: 'T',
      subject: 'Loan Application Pending',
      message:
        'Thank you! We have received your application %% and it is under review.',
      status: 'S',
      updatedDate: 1757451114210,
      acctnbr: '27094',
      bounced: false,
    },
    {
      recipientId: '20961',
      recipientAddress: '2102221000',
      recipientParameters: 'Ezekiel,26994,PEN',
      messageType: 'T',
      subject: 'Loan Application Pending',
      message:
        'Thank you! We have received your application %% and it is under review.',
      status: 'S',
      updatedDate: 1757451114210,
      acctnbr: '26994',
      bounced: false,
    },
    {
      recipientId: '20961',
      recipientAddress: '0000259322',
      recipientParameters: 'Ezekiel,26993,PEN',
      messageType: 'T',
      subject: 'Loan Application Pending',
      message:
        'Thank you! We have received your application %% and it is under review.',
      status: 'S',
      updatedDate: 1757451114210,
      acctnbr: '26993',
      bounced: false,
    },
    {
      recipientId: '20961',
      recipientAddress: '2102221000',
      recipientParameters: 'Ezekiel,26993,PEN',
      messageType: 'T',
      subject: 'Loan Application Pending',
      message:
        'Thank you! We have received your application %% and it is under review.',
      status: 'S',
      updatedDate: 1757451114210,
      acctnbr: '26993',
      bounced: false,
    },
    {
      recipientId: '20961',
      recipientAddress: '2102221000',
      recipientParameters: 'Ezekiel,26992,PEN',
      messageType: 'T',
      subject: 'Loan Application Pending',
      message:
        'Thank you! We have received your application %% and it is under review.',
      status: 'S',
      updatedDate: 1757451114210,
      acctnbr: '26992',
      bounced: false,
    },
    {
      recipientId: '20961',
      recipientAddress: '2102221000',
      recipientParameters: 'Ezekiel,27260,PEN',
      messageType: 'T',
      subject: 'Loan Application Pending',
      message:
        'Thank you! We have received your application %% and it is under review.',
      status: 'S',
      updatedDate: 1757451113838,
      acctnbr: '27260',
      bounced: false,
    },
    {
      recipientId: '20961',
      recipientAddress: '2102221000',
      recipientParameters: '26992,PEN,PL',
      messageType: 'T',
      subject: 'Loan Application Pending',
      message:
        'Thank you! We have received your application %% and it is under review.',
      status: 'S',
      updatedDate: 1757447654828,
      acctnbr: null,
      bounced: false,
    },
    {
      recipientId: '20961',
      recipientAddress: '2102221000',
      recipientParameters: 'Ezekiel,27264,PEN',
      messageType: 'T',
      subject: 'Loan Application Pending',
      message:
        'Thank you! We have received your application %% and it is under review.',
      status: 'S',
      updatedDate: 1757457105148,
      acctnbr: '27264',
      bounced: false,
    },
    {
      recipientId: '20961',
      recipientAddress: '2102221000',
      recipientParameters: 'Ezekiel,4191310,PEN',
      messageType: 'T',
      subject: 'Loan Application Pending',
      message:
        'Thank you! We have received your application %% and it is under review.',
      status: 'S',
      updatedDate: 1757520987439,
      acctnbr: '4191310',
      bounced: false,
    },
    {
      recipientId: '20961',
      recipientAddress: '2102221000',
      recipientParameters: 'Ezekiel,43276,PEN',
      messageType: 'T',
      subject: 'Loan Application Pending',
      message:
        'Thank you! We have received your application %% and it is under review.',
      status: 'S',
      updatedDate: 1757520987439,
      acctnbr: '43276',
      bounced: false,
    },
    {
      recipientId: '20961',
      recipientAddress: '2102221000',
      recipientParameters: '27836,PEN,PL',
      messageType: 'T',
      subject: 'Loan Application Pending',
      message:
        'Thank you! We have received your application %% and it is under review.',
      status: 'S',
      updatedDate: 1757363590336,
      acctnbr: null,
      bounced: false,
    },
    {
      recipientId: '20961',
      recipientAddress: '0000259322',
      recipientParameters: '27094,PEN,PL',
      messageType: 'T',
      subject: 'Loan Application Pending',
      message:
        'Thank you! We have received your application %% and it is under review.',
      status: 'S',
      updatedDate: 1757363590336,
      acctnbr: null,
      bounced: false,
    },
    {
      recipientId: '20961',
      recipientAddress: '2102221000',
      recipientParameters: '27094,PEN,PL',
      messageType: 'T',
      subject: 'Loan Application Pending',
      message:
        'Thank you! We have received your application %% and it is under review.',
      status: 'S',
      updatedDate: 1757363590336,
      acctnbr: null,
      bounced: false,
    },
    {
      recipientId: '20961',
      recipientAddress: '2102221000',
      recipientParameters: '27094,PEN,PL',
      messageType: 'T',
      subject: 'Loan Application Pending',
      message:
        'Thank you! We have received your application %% and it is under review.',
      status: 'S',
      updatedDate: 1757363590336,
      acctnbr: null,
      bounced: false,
    },
    {
      recipientId: '20961',
      recipientAddress: '2102221000',
      recipientParameters: '26994,PEN,PL',
      messageType: 'T',
      subject: 'Loan Application Pending',
      message:
        'Thank you! We have received your application %% and it is under review.',
      status: 'S',
      updatedDate: 1757363590336,
      acctnbr: null,
      bounced: false,
    },
    {
      recipientId: '20961',
      recipientAddress: '2102221000',
      recipientParameters: '27836,PEN,PL',
      messageType: 'T',
      subject: 'Loan Application Pending',
      message:
        'Thank you! We have received your application %% and it is under review.',
      status: 'S',
      updatedDate: 1757436024436,
      acctnbr: null,
      bounced: false,
    },
    {
      recipientId: '20961',
      recipientAddress: '0000259322',
      recipientParameters: '27094,PEN,PL',
      messageType: 'T',
      subject: 'Loan Application Pending',
      message:
        'Thank you! We have received your application %% and it is under review.',
      status: 'S',
      updatedDate: 1757436024436,
      acctnbr: null,
      bounced: false,
    },
    {
      recipientId: '20961',
      recipientAddress: '2102221000',
      recipientParameters: '27094,PEN,PL',
      messageType: 'T',
      subject: 'Loan Application Pending',
      message:
        'Thank you! We have received your application %% and it is under review.',
      status: 'S',
      updatedDate: 1757436024436,
      acctnbr: null,
      bounced: false,
    },
    {
      recipientId: '20961',
      recipientAddress: '2102221000',
      recipientParameters: '27094,PEN,PL',
      messageType: 'T',
      subject: 'Loan Application Pending',
      message:
        'Thank you! We have received your application %% and it is under review.',
      status: 'S',
      updatedDate: 1757436024436,
      acctnbr: null,
      bounced: false,
    },
    {
      recipientId: '20961',
      recipientAddress: '2102221000',
      recipientParameters: '26994,PEN,PL',
      messageType: 'T',
      subject: 'Loan Application Pending',
      message:
        'Thank you! We have received your application %% and it is under review.',
      status: 'S',
      updatedDate: 1757436024436,
      acctnbr: null,
      bounced: false,
    },
    {
      recipientId: '20961',
      recipientAddress: '0000259322',
      recipientParameters: 'Ezekiel,26993,PEN',
      messageType: 'T',
      subject: 'Loan Application Pending',
      message:
        'Thank you! We have received your application %% and it is under review.',
      status: 'S',
      updatedDate: 1757517539383,
      acctnbr: '26993',
      bounced: false,
    },
    {
      recipientId: '20961',
      recipientAddress: '2102221000',
      recipientParameters: 'Ezekiel,26993,PEN',
      messageType: 'T',
      subject: 'Loan Application Pending',
      message:
        'Thank you! We have received your application %% and it is under review.',
      status: 'S',
      updatedDate: 1757517539383,
      acctnbr: '26993',
      bounced: false,
    },
    {
      recipientId: '20961',
      recipientAddress: '2102221000',
      recipientParameters: 'Ezekiel,26992,PEN',
      messageType: 'T',
      subject: 'Loan Application Pending',
      message:
        'Thank you! We have received your application %% and it is under review.',
      status: 'S',
      updatedDate: 1757517539383,
      acctnbr: '26992',
      bounced: false,
    },
    {
      recipientId: '20961',
      recipientAddress: '2102221000',
      recipientParameters: 'Ezekiel,27260,PEN',
      messageType: 'T',
      subject: 'Loan Application Pending',
      message:
        'Thank you! We have received your application %% and it is under review.',
      status: 'S',
      updatedDate: 1757517539383,
      acctnbr: '27260',
      bounced: false,
    },
    {
      recipientId: '20961',
      recipientAddress: '2102221000',
      recipientParameters: 'Ezekiel,27836,PEN',
      messageType: 'T',
      subject: 'Loan Application Pending',
      message:
        'Thank you! We have received your application %% and it is under review.',
      status: 'S',
      updatedDate: 1757517539383,
      acctnbr: '27836',
      bounced: false,
    },
    {
      recipientId: '20961',
      recipientAddress: '0000259322',
      recipientParameters: 'Ezekiel,27094,PEN',
      messageType: 'T',
      subject: 'Loan Application Pending',
      message:
        'Thank you! We have received your application %% and it is under review.',
      status: 'S',
      updatedDate: 1757517539383,
      acctnbr: '27094',
      bounced: false,
    },
    {
      recipientId: '20961',
      recipientAddress: '2102221000',
      recipientParameters: 'Ezekiel,27094,PEN',
      messageType: 'T',
      subject: 'Loan Application Pending',
      message:
        'Thank you! We have received your application %% and it is under review.',
      status: 'S',
      updatedDate: 1757517539383,
      acctnbr: '27094',
      bounced: false,
    },
    {
      recipientId: '20961',
      recipientAddress: '2102221000',
      recipientParameters: 'Ezekiel,27094,PEN',
      messageType: 'T',
      subject: 'Loan Application Pending',
      message:
        'Thank you! We have received your application %% and it is under review.',
      status: 'S',
      updatedDate: 1757517539383,
      acctnbr: '27094',
      bounced: false,
    },
    {
      recipientId: '20961',
      recipientAddress: '2102221000',
      recipientParameters: 'Ezekiel,26994,PEN',
      messageType: 'T',
      subject: 'Loan Application Pending',
      message:
        'Thank you! We have received your application %% and it is under review.',
      status: 'S',
      updatedDate: 1757517539383,
      acctnbr: '26994',
      bounced: false,
    },
    {
      recipientId: '20961',
      recipientAddress: '2102221000',
      recipientParameters: 'Ezekiel,27839,PEN',
      messageType: 'T',
      subject: 'Loan Application Pending',
      message:
        'Thank you! We have received your application %% and it is under review.',
      status: 'F',
      updatedDate: 1757527001421,
      acctnbr: '27839',
      bounced: false,
    },
    {
      recipientId: '20961',
      recipientAddress: '2102221000',
      recipientParameters: 'Ezekiel,27357,PEN',
      messageType: 'T',
      subject: 'Loan Application Pending',
      message:
        'Thank you! We have received your application %% and it is under review.',
      status: 'F',
      updatedDate: 1757527001421,
      acctnbr: '27357',
      bounced: false,
    },
    {
      recipientId: '20961',
      recipientAddress: '2103544425',
      recipientParameters: 'Ezekiel,27826,PEN',
      messageType: 'T',
      subject: 'Loan Application Pending',
      message:
        'Thank you! We have received your application %% and it is under review.',
      status: 'F',
      updatedDate: 1757527001421,
      acctnbr: '27826',
      bounced: false,
    },
    {
      recipientId: '20961',
      recipientAddress: '2102221000',
      recipientParameters: 'Ezekiel,27831,PEN',
      messageType: 'T',
      subject: 'Loan Application Pending',
      message:
        'Thank you! We have received your application %% and it is under review.',
      status: 'F',
      updatedDate: 1757527001421,
      acctnbr: '27831',
      bounced: false,
    },
  ],
};
